### ISSUE TITLE
i cant connect app android to pc

### ISSUE THREAD

**Issue by angkas4** [hagronnestad/Wifi-Barcode-Scanner-Client#1]
i cant connect zinx android app to pc , there are no option in zinx barcode scanner to connect to pc

**Comment by hagronnestad** [comment]
The connection should be automatic. As long as your phone and PC are on the same network and you've followed the instructions to download the client application to your PC, everything should just work.

This library is only needed if you intend to integrate the scanner in your own system.

Please provide more information if you still have issues.

**Comment by angkas4** [comment]
on android app zxing barcode scanner haven't option for connect to pc ,
even though phone and PC has on the same network

Pada tanggal Kam, 18 Jul 2019 pukul 17.00 Hein Andre Grønnestad <
notifications@github.com> menulis:

**Comment by angkas4** [comment]
can you give me a tutorial video, please?

Pada tanggal Jum, 19 Jul 2019 pukul 03.54 roni angkasa <
roniangkas4@gmail.com> menulis:

**Comment by hagronnestad** [comment]
ZXing Barcode Scanner is not my app. This is my app: https://play.google.com/store/apps/details?id=no.hag.android.barcodescannerforpc&hl=en_US

It does use ZXing for the actual scanning, but you're not supposed to use ZXing directly if you want to scan to your PC.
